# Generated by Django 5.2.9 on 2026-01-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add new books to the system'), ('can_change_book', 'can edit existing book details'), ('can_delete_book', 'can remove books from database')]},
        ),
    ]
